export const HENT_VEILEDER_FORESPURT = 'HENT_VEILEDER_FORESPURT';
export const HENTER_VEILEDER = 'HENTER_VEILEDER';
export const HENT_VEILEDER_FEILET = 'HENT_VEILEDER_FEILET';
export const VEILEDER_HENTET = 'VEILEDER_HENTET';

export const HENT_ENHETER_FORESPURT = 'HENT_ENHETER_FORESPURT';
export const HENTER_ENHETER = 'HENTER_ENHETER';
export const HENT_ENHETER_FEILET = 'HENT_ENHETER_FEILET';
export const ENHETER_HENTET = 'ENHETER_HENTET';

export const TOGGLE_MENY = 'TOGGLE_MENY';

export const VIS_FEILMELDING = 'VIS_FEILMELDING';
export const FJERN_FEILMELDING = 'FJERN_FEILMELDING';
