export const HENT_SAKSBEHANDLER_FORESPURT = 'HENT_SAKSBEHANDLER_FORESPURT';
export const HENTER_SAKSBEHANDLER = 'HENTER_SAKSBEHANDLER';
export const HENT_SAKSBEHANDLER_FEILET = 'HENT_SAKSBEHANDLER_FEILET';
export const SAKSBEHANDLER_HENTET = 'SAKSBEHANDLER_HENTET';
