export const HENT_SAKSBEHANDLER_FORESPURT = 'HENT_SAKSBEHANDLER_FORESPURT';
export const HENT_SAKSBEHANDLER_FEILET = 'HENT_SAKSBEHANDLER_FEILET';
export const SAKSBEHANDLER_HENTET = 'SAKSBEHANDLER_HENTET';
export const HENTER_SAKSBEHANDLER = 'HENTER_SAKSBEHANDLER';

export const HENT_ENHETER_FORESPURT = 'HENT_ENHETER_FORESPURT';
export const HENT_ENHETER_FEILET = 'HENT_ENHETER_FEILET';
export const ENHETER_HENTET = 'ENHETER_HENTET';
export const HENTER_ENHETER = 'HENTER_ENHETER';

export const TOGGLE_MENY = 'TOGGLE_MENY';
